# Site information
site_name: Crystalflxme Docs
site_url: https://crystalflxme.github.io/docs/
site_author: Crystalflxme
site_description: The documentation for various projects of mine.

# Customization
theme:
    name: material
    features:
        - tabs

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/crystalflxme
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/crystalflxme

markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.keys
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.mark
    - pymdownx.betterem:
        smart_enable: all

# Site navigation
nav:
    - Home: index.md
    - ChatPlus:
        - Welcome: chatplus/index.md
        - Examples: chatplus/examples.md
        - Setup:
            - Getting started: chatplus/setup/getting-started.md
            - System gotchas: chatplus/setup/gotchas.md
            - Editing the config: chatplus/setup/config.md
            - Dynamic client chat options: chatplus/setup/dynamic-client-chat-options.md
        - API:
            - SpeakerPlus: chatplus/api/speakerplus.md
            - Util: chatplus/api/util.md
        - GitHub Page: https://github.com/Crystalflxme/ChatPlus
    - Cooldown:
        - Welcome: cooldown/index.md
        - Documentation: cooldown/documentation.md
        - GitHub Page: https://github.com/Crystalflxme/Cooldown